### ISSUE TITLE
Invalid `prisma.account.findUnique()` invocation: Provided Int, expected String.

### ISSUE THREAD

**Issue by MatthewCaseres** [nextauthjs/adapters#144] opened 2021-06-25 18:12 UTC
Reproduction: https://github.com/MatthewCaseres/next-auth-prisma-reproduction
I'm using GitHub as my OAuth provider and have had some trouble with the following error message:
```
[next-auth][error][prisma__get_user_by_provider_account_id_error] 
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 43053796
                         ~~~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 43053796 on prisma.findUniqueAccount. Provided Int, expected String.


    at Document.validate (/Users/matthewcaseres/Documents/programming experiments/next-auth-prisma-reproduction/node_modules/@prisma/client/runtime/index.js:32546:19)
    at NewPrismaClient._executeRequest (/Users/matthewcaseres/Documents/programming experiments/next-auth-prisma-reproduction/node_modules/@prisma/client/runtime/index.js:34652:17)
    at consumer (/Users/matthewcaseres/Documents/programming experiments/next-auth-prisma-reproduction/node_modules/@prisma/client/runtime/index.js:34597:23)
    at /Users/matthewcaseres/Documents/programming experiments/next-auth-prisma-reproduction/node_modules/@prisma/client/runtime/index.js:34599:47
    at AsyncResource.runInAsyncScope (node:async_hooks:197:9)
    at NewPrismaClient._request (/Users/matthewcaseres/Documents/programming experiments/next-auth-prisma-reproduction/node_modules/@prisma/client/runtime/index.js:34599:25)
    at Object.then (/Users/matthewcaseres/Documents/programming experiments/next-auth-prisma-reproduction/node_modules/@prisma/client/runtime/index.js:34707:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  clientVersion: '2.25.0'
}
```

**Comment by balazsorban44** [comment] 2021-06-25 19:40
Duplicate of #129 #130 #138

**Closed by balazsorban44** 2021-06-25 19:40 UTC
