### ISSUE TITLE
allow prisma v3

### ISSUE THREAD

**Issue by sachinraja** [nextauthjs/adapters#212] opened 2021-09-09 01:42 UTC
[Prisma released version 3 a couple days ago](https://github.com/prisma/prisma/releases/tag/3.0.1) so it would be great to allow users to install it. The blocker seems to be [`@next-auth/prisma-legacy-adapter`](https://github.com/nextauthjs/adapters/blob/main/packages/prisma-legacy/package.json#L37), which is a dependency of `next-auth`. Looking at the breaking changes there, changes to the package should be none or minimal as they seem to be mostly on the user side. Tests will probably need updating if the `devDependencies` version is updated though.

If the legacy adapter is no longer being maintained, then I suggest allowing prisma v3 in its `peerDependencies` anyway, at least until `next-auth@4` is released.

**Comment by balazsorban44** [comment] 2021-09-09 06:55
I don't have plans for doing any changes for the legacy adapter. If you really must use it and the issue is npm 7, have  a ready here how to make it work anyway https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

I haven't checked what Prisma 3 breaks yet, but I'm fairly confident that the new adapter wouldn't need changes:

https://github.com/nextauthjs/adapters/blob/next/packages/prisma/src/index.ts

I'm happy to extend in the peer dependency version on that one, against the `next` branch.

**Comment by sachinraja** [comment] 2021-09-09 10:05
The new adapter already allows version 3:
https://github.com/nextauthjs/adapters/blob/fae5c50d3accac2c4b380f456ef5ffe96402df6b/packages/prisma/package.json#L34

I agree, doesn't look like any changes are necessary. Installing with force is not ideal, but it's an acceptable temporary solution.

**Comment by balazsorban44** [comment] 2021-09-09 10:14
If the new adapter already works correctly, I am inclined to close this. As said, there are no plans to do changes to the legacy adapter, as it is going to be totally removed soon.

**Closed by balazsorban44** 2021-09-09 10:14 UTC
Labels: enhancement, good first issue, prisma

**Comment by sachinraja** [comment] 2021-09-09 12:33
Just to clarify: I'm actually using the new adapter, but since `next-auth` depends on the legacy adapter, the `peerDependencies` there block the install. But that's fine, force installing is just a minor inconvenience and can wait until v4.

**Comment by balazsorban44** [comment] 2021-09-09 13:10
I see. v4 won't have any direct dependencies on any adapters and this problem will just go away!

**Comment by baronnoraz** [comment] 2021-09-10 16:15
@sachinraja I assume this is the error that you were getting

```
Could not resolve dependency:
peer next-auth@">=3.19.2" from @next-auth/prisma-adapter@0.5.4
```

I installed with `--force` as well, but I wasn't entirely certain that was the correct course of action at this point.

**Comment by sachinraja** [comment] 2021-09-10 22:14
That doesn't look right. The error should be for legacy adapter, not the `next-auth` package itself. You may want to run `npm i next-auth@latest`.

**Comment by baronnoraz** [comment] 2021-09-17 21:33
Thanks @sachinraja.  My issue is indeed with the new adapter.  With `next-auth@4.0.0-beta.2` and `@next-auth/prisma-adapter@0.5.2-next.5` I get the following error trying to run `npm install`.  I'll keep looking for a solution.

```
npm ERR! Could not resolve dependency:
npm ERR! peer next-auth@">=4" from @next-auth/prisma-adapter@0.5.2-next.5
```

**Comment by sachinraja** [comment] 2021-09-17 21:50
`>=4` does not match prerelease tags (see [npm docs](https://docs.npmjs.com/cli/v6/using-npm/semver#prerelease-tags)). You will have to force install if you want to use the `4.0.0-beta`.

**Comment by baronnoraz** [comment] 2021-09-18 00:13
🤦 I didn't realize that.  It builds fine using `--force`.  Thank you so much!!!  I've had a difficult time finding the right version combinations, but it all seems to be working with
```
next-auth@4.0.0-beta.2
@next-auth/prisma-adapter@0.5.2-next.5
prisma@3.0.2
@prisma/client@3.0.2
```

**Comment by balazsorban44** [comment] 2021-09-18 00:35
again, apologies for the hard time. 😬 when v4 goes stable, everything should/will be much easier.

**Comment by baronnoraz** [comment] 2021-09-18 01:33
No apologies necessary!! I could never build anything without great people writing awesome libraries like this.
