### ISSUE TITLE
v4 prisma adapter:  getUserByAccount is not a function

### ISSUE THREAD

**Issue by macrozone** [nextauthjs/adapters#209] opened 2021-09-07 12:07 UTC
when using v4 with @next-auth/prisma-adapter, i'll get:

```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error getUserByAccount is not a function {
  message: 'getUserByAccount is not a function',
  stack: 'TypeError: getUserByAccount is not a function\n' +
    '    at Object.callback (webpack-internal:///./node_modules/next-auth/server/routes/callback.js:71:39)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:171:18)\n' +
    '    at async eval (webpack-internal:///./node_modules/next-auth/server/index.js:251:32)\n' +
    '    at async Object.apiResolver (/path/to/project/node_modules/next/dist/server/api-utils.js:101:9)\n' +
    '    at async DevServer.handleApiRequest (/path/to/project/node_modules/next/dist/server/next-server.js:770:9)\n' +
    '    at async Object.fn (/path/to/project/node_modules/next/dist/server/next-server.js:661:37)\n' +
    '    at async Router.execute (/path/to/project/node_modules/next/dist/server/router.js:205:32)\n' +
    '    at async DevServer.run (/path/to/project/node_modules/next/dist/server/next-server.js:841:29)\n' +
    '    at async DevServer.run (/path/to/project/node_modules/next/dist/server/dev/next-dev-server.js:355:20)',
  name: 'TypeError'
}

```

versions i use:

    "next-auth": "4.0.0-beta.2",
    "@next-auth/prisma-adapter": "^0.5.4",

**Comment by balazsorban44** [comment] 2021-09-07 12:17
Duplicate of https://github.com/nextauthjs/adapters/issues/208

**Closed by balazsorban44** 2021-09-07 12:17 UTC

**Comment by macrozone** [comment] 2021-09-07 12:37
@balazsorban44 attention. This is not a duplicate. This is refers to the prisma adapter, which seems to not be updated to v4 or incompatible with it.

there is not a next tag on npm for that: https://www.npmjs.com/package/@next-auth/prisma-adapter

the latest version is 0.5.4 released 21 days ago. There is no newer version.

**Comment by balazsorban44** [comment] 2021-09-07 12:54
As @macrozone said, https://www.npmjs.com/package/@next-auth/prisma-adapter/v/0.5.2-next.5 is the correct version as of writing.

We documented this in the migration, but let me paste in an image for those not willing to follow up links:

![](https://i.imgur.com/v0NErs8.png)

or go to: https://next-auth.js.org/getting-started/upgrade-v4#adapters

Please make sure you read any given documentation precisely, because duplicate issues like this create maintenance overhead.
