### ISSUE TITLE
Error while authenticating with GitHub & the new Prisma adapter

### ISSUE THREAD

**Issue by icflorescu** [nextauthjs/adapters#129] opened 2021-06-08 12:56 UTC
While trying to authenticate with GitHub provider on the new (non-legacy) Prisma adapter configuration, I'm getting this error:

```
[next-auth][error][prisma__get_user_by_provider_account_id_error]
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError:
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 123456
                         ~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 123456 on prisma.findUniqueAccount. Provided Int, expected String.

    at Document.validate (/[...]/node_modules/@prisma/client/runtime/index.js:32898:19)
    at NewPrismaClient._executeRequest (/[...]/node_modules/@prisma/client/runtime/index.js:34840:17)
    at /[...]/node_modules/@prisma/client/runtime/index.js:34775:52
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/[...]/node_modules/@prisma/client/runtime/index.js:34775:25)
    at Object.then (/[...]/node_modules/@prisma/client/runtime/index.js:34895:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '2.24.1'
```

The providerAccountId integer in the above snapshot was changed for obvious privacy reasons.

See https://github.com/nextauthjs/next-auth/issues/2144 for more info.

**Comment by balazsorban44** [comment] 2021-06-08 15:51
duplicate of #130

**Closed by balazsorban44** 2021-06-08 15:51 UTC

**Comment by icflorescu** [comment] 2021-06-08 18:26
I'll leave this note here for the benefit of other people who might run into the same issue.

Until this gets fixed, use this workaround:

```ts
import NextAuth, { User as NextAuthUser } from 'next-auth'
interface NextAuthUserWithStringId extends NextAuthUser {
  id: string
}
...
Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      profile(profile) {
        return {
          id: profile.id.toString(),
          name: profile.name || profile.login,
          email: profile.email,
          image: profile.avatar_url,
        } as NextAuthUserWithStringId
      },
    }),
...
```
